### basic route group
GET {{baseUrl}}/v1/info

### route group with route parameters
GET {{baseUrl}}/v1/person/13/child/Murat

### link to resource, can be used in HATEOS
GET {{baseUrl}}/v1/person/12/link